#!/bin/bash
#
# Copyright and License information can be found in the file
# license.txt or license.html
#
# This script builds the testlist.h file that is included in the 
# reporter.h file that builds the reporter, see the top Makefile 
# for dependency.
#
# This scripts uses:
#   rule_list - the list of rules in TS 17961, each rule is a directory
#   check_list.awk - this awk script opens each test file to verify that
#                    the documentation on the line of code required to 
#                    trigger a diagnostic is correct.  If no diagnostic
#                    is required a '0' is used.  If the documentation and
#                    code do not match a diagnostic is issued.
#   make_struct.awk - The awk script takes the file generated by check_list.awk
#                     and builds the testlist.h file.  
#
if [ -e file-list ]
then
 rm -f file-list
fi

while read line
do
 echo $line | grep -q '#' > /dev/null
 if [ $? -ne 0 ]
 then
  ls -1 $line/*.[c,h] >> file-list
 fi
done < rule_list

while read line 
do 
 awk -f check_list.awk $line 
done < file-list > chked-file-list

grep -q "+++" chked-file-list > /dev/null

if [ $? -eq 0 ]
then
  echo Following need to be checked, documentation does not match code.
  echo
  grep "+++" chked-file-list
  exit 0
fi
 
if [ -x make_struct.awk ]
then
 awk -f make_struct.awk chked-file-list > ../include/testlist.h
else
 echo make_struct.awk is not present or executable
 exit 0
fi

rm chked-file-list
rm file-list
